"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var DestructorEstelar_1 = require("./Naves/DestructorEstelar");
var HalconMilenario_1 = require("./Naves/HalconMilenario");
var Tripulante_1 = require("./Personas/Tripulante");
var Pasajero_1 = require("./Personas/Pasajero");
var destructorEstelar = new DestructorEstelar_1.DestructorEstelar();
var halconMilenario = new HalconMilenario_1.HalconMilenario();
var tripulante1 = new Tripulante_1.Tripulante('Leandro');
var tripulante2 = new Tripulante_1.Tripulante('Jorge');
var pasajero = new Pasajero_1.Pasajero('Darth Vader');
halconMilenario.agregarTripulante(tripulante1);
halconMilenario.agregarTripulante(tripulante2);
destructorEstelar.agregarPasajero(pasajero);
destructorEstelar.mostrarPersonasABordo();
halconMilenario.mostrarPersonasABordo();
destructorEstelar.despegar();
halconMilenario.despegar();
halconMilenario.prepararEscudos();
destructorEstelar.atacar(halconMilenario);
